// Who Am I - Character Database
// Bilingual support: English (en) and Kurdish Sorani (ku)

export const CATEGORIES = {
    celebrities: {
        name: { en: 'Celebrities', ku: 'ئەستێرەکان' },
        icon: 'star',
        items: [
            { en: 'Taylor Swift', ku: 'تەیلەر سویفت' },
            { en: 'Dwayne Johnson', ku: 'دوەین جۆنسن (ڕۆک)' },
            { en: 'Beyoncé', ku: 'بیۆنسێ' },
            { en: 'Leonardo DiCaprio', ku: 'لیۆناردۆ دیکاپریۆ' },
            { en: 'Tom Hanks', ku: 'تۆم هانکس' },
            { en: 'Rihanna', ku: 'ڕیهانا' },
            { en: 'Brad Pitt', ku: 'براد پیت' },
            { en: 'Will Smith', ku: 'ویل سمیث' },
            { en: 'Lady Gaga', ku: 'لەیدی گاگا' },
            { en: 'Morgan Freeman', ku: 'مۆرگان فریمان' },
            { en: 'Ryan Reynolds', ku: 'ڕایان ڕێنۆڵدز' },
            { en: 'Ariana Grande', ku: 'ئاریانا گراندی' },
            { en: 'Robert Downey Jr.', ku: 'ڕۆبێرت داونی' },
            { en: 'Keanu Reeves', ku: 'کیانو ڕیڤز' },
            { en: 'Selena Gomez', ku: 'سەلینا گۆمێز' },
            { en: 'Ed Sheeran', ku: 'ئێد شیران' },
            { en: 'Billie Eilish', ku: 'بیلی ئەیلیش' },
            { en: 'Cristiano Ronaldo', ku: 'کریستیانۆ ڕۆناڵدۆ' },
            { en: 'Lionel Messi', ku: 'لیۆنێل مەسی' },
            { en: 'Elon Musk', ku: 'ئیلۆن ماسک' },
            { en: 'Tom Cruise', ku: 'تۆم کروز' },
            { en: 'Dua Lipa', ku: 'دوا لیپا' },
            { en: 'Shakira', ku: 'شاکیرا' },
            { en: 'Neymar', ku: 'نەیمار' },
            { en: 'Kylian Mbappé', ku: 'کیلیان مباپێ' },
            { en: 'LeBron James', ku: 'لێبرۆن جەیمز' },
            { en: 'Justin Bieber', ku: 'جاستن بیبەر' },
            { en: 'Eminem', ku: 'ئیمینەم' },
            { en: 'Drake', ku: 'درەیک' },
            { en: 'Jackie Chan', ku: 'جاکی چان' },
        ],
    },
    movies: {
        name: { en: 'Movie Characters', ku: 'کارەکتەرەکانی فیلم' },
        icon: 'film',
        items: [
            { en: 'Harry Potter', ku: 'هاری پۆتەر' },
            { en: 'Darth Vader', ku: 'دارث ڤەیدەر' },
            { en: 'Jack Sparrow', ku: 'جاک سپارۆ' },
            { en: 'Iron Man', ku: 'ئایرۆن مان' },
            { en: 'Elsa (Frozen)', ku: 'ئێلسا (فرۆزن)' },
            { en: 'Batman', ku: 'باتمان' },
            { en: 'Joker', ku: 'جۆکەر' },
            { en: 'Spider-Man', ku: 'سپایدەرمان' },
            { en: 'Shrek', ku: 'شرێک' },
            { en: 'James Bond', ku: 'جەیمس بۆند' },
            { en: 'Gandalf', ku: 'گاندالف' },
            { en: 'Thanos', ku: 'ثانۆس' },
            { en: 'Forrest Gump', ku: 'فۆرێست گامپ' },
            { en: 'Terminator', ku: 'تێرمینەیتەر' },
            { en: 'Yoda', ku: 'یۆدا' },
            { en: 'Wonder Woman', ku: 'وەندەر ومان' },
            { en: 'Deadpool', ku: 'دێدپوول' },
            { en: 'Black Panther', ku: 'بلاک پانثەر' },
            { en: 'Hermione Granger', ku: 'هێرمایۆنی گرەینجەر' },
            { en: 'Captain America', ku: 'کاپتن ئەمریکا' },
            { en: 'Thor', ku: 'سۆڕ' },
            { en: 'Hulk', ku: 'هەڵک' },
            { en: 'Groot', ku: 'گروت' },
            { en: 'Wolverine', ku: 'ووڵڤەرین' },
            { en: 'Darth Maul', ku: 'دارث مۆل' },
            { en: 'Loki', ku: 'لۆکی' },
            { en: 'Obi-Wan Kenobi', ku: 'ئۆبی وان کەنۆبی' },
            { en: 'Katniss Everdeen', ku: 'کاتنیس ئیڤەردین' },
            { en: 'Neo', ku: 'نیو' },
        ],
    },
    cartoons: {
        name: { en: 'Cartoon Characters', ku: 'کارەکتەرەکانی کارتۆن' },
        icon: 'happy',
        items: [
            { en: 'SpongeBob', ku: 'سپۆنج بۆب' },
            { en: 'Mickey Mouse', ku: 'میکی ماوس' },
            { en: 'Bugs Bunny', ku: 'باگز بانی' },
            { en: 'Pikachu', ku: 'پیکاچو' },
            { en: 'Homer Simpson', ku: 'هۆمەر سیمپسۆن' },
            { en: 'Scooby-Doo', ku: 'سکوبی دوو' },
            { en: 'Tom (Tom & Jerry)', ku: 'تۆم (تۆم و جێری)' },
            { en: 'Dora the Explorer', ku: 'دۆرا گەشتیار' },
            { en: 'Patrick Star', ku: 'پاتریک ئەستێرە' },
            { en: 'Bart Simpson', ku: 'بارت سیمپسۆن' },
            { en: 'Sonic the Hedgehog', ku: 'سۆنیک' },
            { en: 'Mario', ku: 'ماریۆ' },
            { en: 'Donald Duck', ku: 'دۆناڵد داک' },
            { en: 'Tweety Bird', ku: 'توویتی' },
            { en: 'Garfield', ku: 'گارفیڵد' },
            { en: 'Winnie the Pooh', ku: 'وینی پوو' },
            { en: 'Peppa Pig', ku: 'پێپا پیگ' },
            { en: 'Minions', ku: 'مینیۆنز' },
            { en: 'Elmo', ku: 'ئێلمۆ' },
            { en: 'Goku', ku: 'گۆکو' },
            { en: 'Naruto', ku: 'ناروتۆ' },
            { en: 'Sailor Moon', ku: 'سەیلۆر موون' },
            { en: 'Popeye', ku: 'پۆپای' },
            { en: 'Dexter', ku: 'دێکستەر' },
            { en: 'Courage the Cowardly Dog', ku: 'کۆرەیج سەگە ترسنۆکەکە' },
            { en: 'Powerpuff Girls', ku: 'کچانی بەهێز' },
            { en: 'Finn the Human', ku: 'فینی مرۆڤ' },
            { en: 'Jake the Dog', ku: 'جەیکی سەگ' },
            { en: 'Oggy', ku: 'ئۆگی' },
        ],
    },
    animals: {
        name: { en: 'Animals', ku: 'ئاژەڵەکان' },
        icon: 'paw',
        items: [
            { en: 'Lion', ku: 'شێر' },
            { en: 'Elephant', ku: 'فیل' },
            { en: 'Penguin', ku: 'پێنگوین' },
            { en: 'Dolphin', ku: 'دۆلفین' },
            { en: 'Giraffe', ku: 'زەڕافە' },
            { en: 'Tiger', ku: 'بەور' },
            { en: 'Panda', ku: 'پاندا' },
            { en: 'Kangaroo', ku: 'کانگرۆ' },
            { en: 'Eagle', ku: 'هەڵۆ' },
            { en: 'Shark', ku: 'قرش' },
            { en: 'Octopus', ku: 'هەشتپێ' },
            { en: 'Koala', ku: 'کۆئالا' },
            { en: 'Wolf', ku: 'گورگ' },
            { en: 'Owl', ku: 'کوندەپەپوو' },
            { en: 'Butterfly', ku: 'پەپوولە' },
            { en: 'Crocodile', ku: 'تمساح' },
            { en: 'Peacock', ku: 'تاووس' },
            { en: 'Sloth', ku: 'ئاژەڵی تەمبەڵ' },
            { en: 'Cheetah', ku: 'چیتا' },
            { en: 'Whale', ku: 'نەهەنگ' },
            { en: 'Rhino', ku: 'کەرگەدەن' },
            { en: 'Hippo', ku: 'ئەسپی ئاوی' },
            { en: 'Camel', ku: 'وشتر' },
            { en: 'Gorilla', ku: 'گۆڕێلا' },
            { en: 'Flamingo', ku: 'فلامینگۆ' },
            { en: 'Seahorse', ku: 'ئەسپی دەریایی' },
            { en: 'Lobster', ku: 'لۆبستەر' },
            { en: 'Polar Bear', ku: 'ورچی جەمسەری' },
            { en: 'Chameleon', ku: 'حیربا' },
        ],
    },

    professions: {
        name: { en: 'Professions', ku: 'پیشەکان' },
        icon: 'briefcase',
        items: [
            { en: 'Doctor', ku: 'پزیشک' },
            { en: 'Firefighter', ku: 'ئاگرکوژێنەوە' },
            { en: 'Astronaut', ku: 'ئاسمانەوان' },
            { en: 'Chef', ku: 'چێشتلێنەر' },
            { en: 'Police Officer', ku: 'پۆلیس' },
            { en: 'Teacher', ku: 'مامۆستا' },
            { en: 'Pilot', ku: 'فڕۆکەوان' },
            { en: 'Scientist', ku: 'زانا' },
            { en: 'Artist', ku: 'هونەرمەند' },
            { en: 'Musician', ku: 'میوزیکژەن' },
            { en: 'Farmer', ku: 'جوتیار' },
            { en: 'Detective', ku: 'لێکۆڵەر' },
            { en: 'Nurse', ku: 'پەرستار' },
            { en: 'Architect', ku: 'تەلارساز' },
            { en: 'Photographer', ku: 'وێنەگر' },
            { en: 'Veterinarian', ku: 'پزیشکی ئاژەڵ' },
            { en: 'Magician', ku: 'جادووگەر' },
            { en: 'Athlete', ku: 'وەرزشوان' },
            { en: 'Judge', ku: 'دادوەر' },
            { en: 'Sailor', ku: 'کەشتیوان' },
            { en: 'Electrician', ku: 'کارەباکار' },
            { en: 'Plumber', ku: 'لولەکار' },
            { en: 'Carpenter', ku: 'نەجار' },
            { en: 'Taxi Driver', ku: 'شۆفێری تاکسی' },
            { en: 'Dentist', ku: 'پزیشکی ددان' },
            { en: 'Surgeon', ku: 'جەراح' },
            { en: 'Psychologist', ku: 'پسیکۆلۆژیست' },
            { en: 'Journalist', ku: 'ڕۆژنامەنووس' },
            { en: 'Programmer', ku: 'بەرنامەساز' },
        ],
    },
    historical: {
        name: { en: 'Historical Figures', ku: 'کەسایەتییە مێژووییەکان' },
        icon: 'book',
        items: [
            { en: 'Albert Einstein', ku: 'ئەلبێرت ئاینشتاین' },
            { en: 'Cleopatra', ku: 'کلیۆپاترا' },
            { en: 'Napoleon Bonaparte', ku: 'نەپۆلیۆن بۆناپارت' },
            { en: 'Alexander the Great', ku: 'ئەسکەندەری گەورە' },
            { en: 'Julius Caesar', ku: 'یولیۆس قەیسەر' },
            { en: 'Mahatma Gandhi', ku: 'مەهاتما گاندی' },
            { en: 'Nelson Mandela', ku: 'نێلسن ماندێلا' },
            { en: 'Abraham Lincoln', ku: 'ئەبراهام لینکۆڵن' },
            { en: 'Nikola Tesla', ku: 'نیکۆلا تێسلا' },
            { en: 'Isaac Newton', ku: 'ئیسحاق نیوتن' },
            { en: 'Thomas Edison', ku: 'تۆماس ئێدیسۆن' },
            { en: 'Martin Luther King Jr.', ku: 'مارتن لوثەر کینگ' },
            { en: 'Saladin', ku: 'سەلاحەدینی ئەییووبی' },
            { en: 'Genghis Khan', ku: 'جەنگیز خان' },
            { en: 'Adolf Hitler', ku: 'ئادۆلف هیتلەر' },
            { en: 'Saddam Hussein', ku: 'سەدام حوسێن' },
            { en: 'Che Guevara', ku: 'چێ گێڤارا' },
            { en: 'Leonardo da Vinci', ku: 'لیۆناردۆ دا ڤینچی' },
            { en: 'Marie Curie', ku: 'ماری کوری' },
            { en: 'Shakespeare', ku: 'شێکسپیر' },
            { en: 'Christopher Columbus', ku: 'کریستۆفەر کۆلۆمبۆس' },
            { en: 'Winston Churchill', ku: 'وینستن چێرچل' },
            { en: 'Mustafa Kemal Atatürk', ku: 'مستەفا کەمال ئاتاتورک' },
            { en: 'Queen Elizabeth II', ku: 'شاژن ئیلیزابێثی دووەم' },
        ],
    },
    foodDrinks: {
        name: { en: 'Food & Drinks', ku: 'خواردن و خواردنەوە' },
        icon: 'Utensils',
        items: [
            { en: 'Pizza', ku: 'پیتزا' },
            { en: 'Sushi', ku: 'سوشی' },
            { en: 'Hamburger', ku: 'هامبەرگەر' },
            { en: 'Chocolate', ku: 'چوکولاتە' },
            { en: 'Ice Cream', ku: 'ئایسکرێم' },
            { en: 'Coffee', ku: 'قاوە' },
            { en: 'Tea', ku: 'چا' },
            { en: 'Kebab', ku: 'کەباب' },
            { en: 'Dolma', ku: 'یاپراخ' },
            { en: 'Biryani', ku: 'بریانی' },
            { en: 'Pasta', ku: 'پاستا' },
            { en: 'Taco', ku: 'تاکۆ' },
            { en: 'Popcorn', ku: 'پۆپکۆرن' },
            { en: 'Lemonade', ku: 'لیمۆنەید' },
            { en: 'Banana', ku: 'مۆز' },
        ],
    },
};

// Helper to get item text based on language
export const getItemText = (item, language = 'en') => {
    if (typeof item === 'string') return item; // backwards compatibility
    return item[language] || item.en;
};

// Helper to get category name based on language
export const getCategoryName = (category, language = 'en') => {
    if (typeof category.name === 'string') return category.name;
    return category.name[language] || category.name.en;
};

export const getRandomCharacter = (categoryKey, language = 'en') => {
    const category = CATEGORIES[categoryKey];
    if (!category) return null;
    const items = category.items;
    const item = items[Math.floor(Math.random() * items.length)];
    return getItemText(item, language);
};

export const getAllCategories = (language = 'en') => {
    return Object.entries(CATEGORIES).map(([key, value]) => ({
        key,
        name: getCategoryName(value, language),
        icon: value.icon,
        count: value.items.length,
    }));
};
